[package]
name = "avail-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
subxt = { version = "0.29" }
avail-subxt = { git = "https://github.com/availproject/avail", branch = "main", version = "0.4.0" }
codec = { package = "parity-scale-codec", version = "3.6.1" }
prettytable = "0.10.0"
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v1.0.0", version = "16.0.0" }
structopt = "0.3.26"
tokio = "1.34.0"
